### PR TITLE
Chapter 7 and 8 spelling/grammar/wording

### PR DESCRIPTION
**Pull request by wibblymat**
I changed a couple of British English spellings to US English (ise => ize) since that seemed to be how the rest of the book is written.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thank you, @wibblymat. These are sensible changes. If you have time could you rebase against master? :)

**Comment by addyosmani** [comment]
Note that as part of your suggestions for chapter re-arrangement, the 7 and 8 this applied to may have been moved around.

**Comment by wibblymat** [comment]
I'm nearly done reviewing, will come back to this when its all sent off - should be in the next couple of days.

**Comment by wibblymat** [comment]
Oh, wow, I hate rebasing PR requests. A diff between my branch and gh-pages shows only the changes I intended to make with this PR, but Github shows everything.

Just doing `git rebase -i` didn't go quite far back enough to pick up my commit, so I included a really big number of commits to make sure I got it. So it looks even more stupid than it normally would :)

**Comment by addyosmani** [comment]
Is it possible to squash/rebase? It can't currently be merged :)

**Comment by wibblymat** [comment]
Ok... I think that does it, and much cleaner too. Had to do some manual conflict resolution earlier so it is possible that I have undone someone else's changes but I did try to be careful not to.

**Comment by addyosmani** [comment]
Hey @wibblymat. It looks like we might still need some rebasing. Sorry about that!

In case it helps:
- 6 is now extensions
- 7 is common problems
- 8  is modular development
- 9 is bbb

**Pull request closed without merging**
