### PR TITLE
Split the source markdown into chapters (to start #194)

### PR DESCRIPTION
**Pull request by wibblymat**
Since there are no pending PRs, now seemed a good time to bite the bullet.

The build works for the HTML version as before. This does not yet produce one page per chapter in the output; there should not be any noticeable difference to the output.

Doing the split in stages seems to be sensible to me, as does starting with the biggest and most disruptive change.

### CODE REVIEW

**Comment by wibblymat** [comment]
I think I actually wanted to tag #248

**Comment by addyosmani** [comment]
Fantastic work @wibblymat. This was a welcome surprise.

Would you like us to keep this open to track progress or merge portions of the work at a time as you go along?

**Comment by wibblymat** [comment]
@addyosmani I would merge this now if it doesn't cause problems I haven't thought of. It means that people can start working with the split version now without having to keep two versions up to date.

Changing the output of the build will be much less disruptive to other work so can happen alongside without causing too much trouble.

**Comment by addyosmani** [comment]
Sounds good @wibblymat :) I'll do some checks on the split this evening and hopefully merge. Cheers!

**Comment by addyosmani** [comment]
@jackfranklin is this what you had in mind for the split you were thinking of doing? I think @wibblymat's solution is fairly clean and should hopefully make it easier to update individual sections.

**Comment by jackfranklin** [comment]
@addyosmani yeah @wibblymat basically did what I had in mind but beat me to it! :+1:

**Comment by wibblymat** [comment]
Ok, so it is currently broken, though I thought I had tested it earlier to make sure it wasn't.

The third commit, changing image links to be `../img/` rather than just `img/` breaks the HTML version because the images for that are resolved when you view it, not when you build it. The other formats are the other way around.

I'm messing around with pandoc at the moment to see if I can force the base url for a format.

**Comment by addyosmani** [comment]
Thanks for looking into it, @wibblymat! I appreciate you checking to make sure it's building correctly.

**Comment by wibblymat** [comment]
I think that should do it! Split chapters, building output that should be indistinguishable from before.

Time for me to stop getting distracted and contribute something related to the actual text :)

**Comment by addyosmani** [comment]
Awesome work, @wibblymat! It looks great.

One last request: could you check-in a compiled version of index.html so that we have diff records to make sure the output is the same/roughly same as it is using the current setup? :)

**Comment by wibblymat** [comment]
Done, though the existing index.html was ~10 commits behind already so some of the content will have a diff because of that.

**Comment by addyosmani** [comment]
I just reviewed the compiled version and it looks great. Thanks again for all your work on this @wibblymat! Merging.

**Pull request merged**
