### PR TITLE
Complete rewritten Mobile chapter, 2nd pull request

### PR DESCRIPTION
**Pull request by raDiesle**
Complete rewritten Mobile chapter, 2nd pull request,
first, https://github.com/addyosmani/backbone-fundamentals/pull/315

### CODE REVIEW

**Comment by addyosmani** [comment]
cc @dcmaf - thank you so much for the second pull, @raDiesle

**Comment by raDiesle** [comment]
I think it is a good idea to trigger the pull request.
Is the fork rebased correct?

Thanks

**Comment by addyosmani** [comment]
It looks like the pull request can't be automatically merged. Would you like to rebase or create a fresh pull request with only those files that have changed?

**Comment by raDiesle** [comment]
Hm, does this looks better?
If not, I will request some help.

Sorry for inconvenience!

Thanks

**Comment by addyosmani** [comment]
Not at all! It looks like the PR can't be automatically merged but if you would like we can manually bring in the new chapter, update the chapter numbers after it and integrate the content. Would that be easier?

@dcmaf if you get a chance, it would be tremendously useful to get your OK on the content. I'm re-reviewing now but always useful to know if I've missed anything :)

**Comment by dcmaf** [comment]
I'm running through it now and plan on pushing fixes for a few typos. If you can get this updated Mobile chapter merged in then I'll try to give that a read-through as well.

**Comment by addyosmani** [comment]
I've manually merged the updated mobile section in. Thanks so much for your time and effort spent getting this shaped up and written.

@dcmaf I'll leave this open so that we can track/discuss any major changes that are needed. I trust you with any tweaks/typos :)

**Comment by dcmaf** [comment]
In the opening section it says there are two main principles we need to understand. Am I correct in interpreting these to be _progressive enhancement_ and _responsive web design_?

**Comment by raDiesle** [comment]
Yep, if it is not clear, feel free to add information !

**Comment by dcmaf** [comment]
I have submitted a pull request (#395) with my changes. Definitely needs to be reviewed and any loss of meaning/intention corrected!

**Comment by addyosmani** [comment]
With #395 now merged, this chapter should be good to go. A big thank you for all of the help in bringing this together :)

**Comment by raDiesle** [comment]
More was needed to be changed than expected.
Thank you for your support !
I will check again for mistakes.

**Pull request closed without merging**
