### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by glenselle**
This commit changes the word "instantiation" to "instantiate".

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks Glen!

**Comment by glenselle** [comment]
No problem. By the way, would it help if I also made changes and opened a pull request for the other versions of the book like .md, .rtt, .epub and all of the others? I'd be happy to make those changes if that would help.

-Glen

**Comment by addyosmani** [comment]
@glenselle I think just making them to the .md file would be okay. I need to regenerate the other formats soon anyway, but thanks!

**Comment by glenselle** [comment]
Ok, I'll do that.

**Pull request merged**
