### PR TITLE
Editorial pass from start of 'Advanced' section to start of 'Backbone Mobile' section

### PR DESCRIPTION
**Pull request by heyotwell**
Here's another editorial swipe through. Almost entirely small grammar fixes and shortening of sentences. One section where I reorganized a few paragraphs in a way I thought made things clearer.

### CODE REVIEW

**Comment by heyotwell** [comment]
Hmm, not sure why my previous commits showed up again. You can ignore everything before c40c732 for this pull request.

**Comment by addyosmani** [comment]
Thanks @heyotwell. I was wondering the same thing about the previous commits :) No worries! I'll review these today and integrate. Appreciate your time!

**Comment by heyotwell** [comment]
Fewer changes in these last sections. The jQuery Mobile stuff doesn't feel totally integrated yet into the overall content, especially as the testing section at the end is so detailed...maybe consider breaking out the jQM stuff into a separate doc or book entirely? Just a thought.

**Comment by addyosmani** [comment]
@heyotwell 

Thanks!

RE: Mobile

The jQM section currently near the end of the book is really a placeholder for a future chapter and tutorial. I agree it's not that integrated at the moment, but I hope to rectify this in the coming weeks.

RE: BDD

I meant "Jasmine helps both developers". Sorry it wasn't clearer!

**Comment by addyosmani** [comment]
Most of these have been manually merged in over time. Thanks so much once again @heyotwell!

**Pull request closed without merging**
