### PR TITLE
Proposed changes to Chapter 3: Internals

### PR DESCRIPTION
**Pull request by dcmaf**
@Addy - I've finished reviewing Chapter 3: Internals and checked in a bunch of changes (including a proposed new chapter title!). I've added a few new things and expanded on some of the existing discussion, so please check for accuracy.

I've also made recommendations below for moving some of the material at the end of the chapter to later in the book. I think that if I am a reader new to Backbone then what I want out of this chapter is just enough information to get me started and then to move on to the tutorials to solidify what I've learned so far. Thus, the less that is in this chapter, the simpler it will seem to the reader and the less daunting their experience will be.

Marc

Summary of Changes:
- Renamed chapter to Backbone Basics. 'Internals' to me conveyed implementation
  details and sounded intimidating. Something along the lines of 'Basics',
  'Essentials', or 'Core Backbone' sounds like I'm going to learn what I
  need to know in order to use Backbone.
- Added comments in some of the examples showing what the console output would be.
- In some examples, changed logging to use JSON.stringify; otherwise, whole
  object was logged
- Added discussion of invalid event to Validation section. Also added how
  validate is automatically called on save and on set when validate option is true.
  Added validate flag setting in validation example.
- Reworded note about the attributes object passed to validate.
- In 'el' discussion, noted ability to set el when creating view. Also added discussion
  on $el and $().
- Added HTML for example view to the render discussion. Changed checkbox element in
  template to conditionally set checked attribute as is done in the Todo Practical.
  Made same change in chapter 2.
- Removed use of localStorage in Collection examples. Removed create() from initial
  Collection examples so examples work without having a backing store (and without
  introducing the concept at this point). Create() is introduced in the new RESTful
  Persistence section noted below.
- Moved the Backbone.sync portion of the discussion under Fetching models from the
  server to the Backbone.sync discussion later in the chapter.
- Expanded Fetching models from the server section into a new RESTful Persistence
  section which also includes Saving models to the server and Deleting models from
  the server. I think Backbone's persistence support and its ease of integration
  with RESTful servers (I'm using it with Java/Spring MVC) is a key differentiator
  between Backbone and other MV\* frameworks. Please check for accuracy!
- Expanded the Chainable API discussion. I've used chained APIs in Java, but had
  a hard time understanding what was going on in this example until I looked at
  the Underscore documentation and code. Please check my new explanation for
  accuracy!
- General wordsmithing

Recommendations:
- Move Conflict Management to another section (e.g., common problems or appendix)
- Move Inheritance and Mixins to another section
- Keep Dependencies initial section (perhaps state elsewhere), move subsections
  (DOM Manipulation, Utilities, RESTFul Persistence, Routing) to appendix or other
  section focused on Backbone internals
- Consider moving Namespacing discussion to later in the book (e.g., common problems)

Other comments:
- Object literal example is unclear; it contains two 'var myApplication' declarations
  and most of its content in a comment. As a result, what is being recommended is unclear.
- REST sections will need to be updated to discuss HTTP PATCH support.

### CODE REVIEW

**Comment by addyosmani** [comment]
Wow. Now _this_ is a thorough technical review :)



Fantastic work going through the chapter and making all of these suggestions.

On the recommendations, I agree with moving conflict management and inheritance elsewhere as well as namespacing. My initial thought is that we should move these to a more advanced chapter and maybe the appendix isn't the worst place for them. I do want to avoid bloating it up too much, but we could certainly do that for now. Sound good?

On other comments, I agree we should improve the object literal example. It does seem a little awkward at the moment and it doesn't make sense to mostly be comment based.

RE REST: My understanding was that PATCH support landed post 0.9.2. I was initially planning for us to keep 0.9.2 support for the book with 0.9.10/1.0 (when it hits) being documented in the appendix until 1.0 was finalized, however if you think you'll have time to make 0.9.10 recommendations while you're doing the review I'm more than happy to merge them. As mentioned, I could be wrong regarding PATCH support. 

I'm happy to merge this after hearing your thoughts on the above :)

**Comment by dcmaf** [comment]
Thanks for the positive feedback on the feedback; I think my 'technical review' changes will need their own technical reviewing!

I could see moving Conflict Management to the Common Problems chapter along with some added context as to why you might have two versions of Backbone in the same application. Inheritance and Backbone-Super also could go in Common Problems or maybe some other chapter if appropriate. Maybe there could be a design patterns chapter for these issues and other issues - I think it is definitely important to address these real-world application issues once the reader has a good handle on basic Backbone.

On namespaces, it might be worthwhile to introduce the form of namespacing that is used in the tutorials in this chapter and move the discussion of alternatives to an appendix.

Regarding versions, I think the focus should be on getting the O'Reilly print version as consistent as possible with what will be available when the book is published (at least 0.9.10 if not 1.0) - I would think that from a marketing standpoint they would want to be able to put "Supports Backbone 1.0" on the cover. I don't know the material well enough to estimate the impact of bringing the entire book up to 0.9.10 now vs. waiting for 1.0 to get tagged. I would be willing to update chapter 3 (based on your thorough description of the differences in the Appendix) and keep an eye out for other out-of-date content if you decide to update the book to 0.9.10 sooner rather than later. Also, note that it looks like I inadvertently introduced a 0.9.10 feature when I changed the validation discussion to include passing the validate: true flag to set.

**Comment by addyosmani** [comment]
> I could see moving Conflict Management to the Common Problems chapter along with some added context as to why you might have two versions of Backbone in the same application. 

Agreed. Let's do that! 

> Inheritance and Backbone-Super also could go in Common Problems or maybe some other chapter if appropriate. 

I think it could work in Common Problems tbh.

> Maybe there could be a design patterns chapter for these issues and other issues - I think it is definitely important to address these real-world application issues once the reader has a good handle on basic Backbone.

I wanted to shy away from a design patterns chapter as it might cause confusion with the design patterns book I wrote, but I think that as we progress there might be room for something like that if content doesn't fit into problems or the appendix.

> On namespaces, it might be worthwhile to introduce the form of namespacing that is used in the tutorials in this chapter and move the discussion of alternatives to an appendix.

I think that's a sane approach to introducing this content. As the alternatives are more for interest purposes anyway, they do fit better in the appendix.

> Regarding versions, I think the focus should be on getting the O'Reilly print version as consistent as possible with what will be available when the book is published (at least 0.9.10 if not 1.0) 

Hmm. You have a good point there. Okay. How about we say that moving forward all changes should target 0.9.10. We currently have a PR open in #301 to update the Todo app. Do you think you'll have time to check through the PR you submitted for any other code samples that might need an update?

Your suggestions so far have been fantastic. So glad to have you on board.

**Comment by dcmaf** [comment]
Do you want me to update my branch with the moves of those sections and 0.9.10 changes (I could see some additions to the events discussion along with including PATCH in the HTTP parts) before you merge the existing pull request?

**Comment by addyosmani** [comment]
If possible that would be really helpful. I'm happy to merge whenever you're ready.

**Comment by dcmaf** [comment]
Should have it done soon. A few questions:
- In the Backbone's Sync API section, the MyAPI example sets requestContent['resource'] to model.toJSON() but then doesn't do anything with it. Is something missing?
- Is the json2.js support needed for legacy browsers that don't support JSON, legacy servers, or both?
- Since using the events property in a view automatically binds 'this' to the view within the handler method, jQuery's binding of this to the DOM element handling the event is overridden. I take it that event.target is the recommended way of getting to the DOM element on which the event was triggered, but is there a way to get to the handling element that 'this' would have been bound to? Would this always end up being this.el?

**Comment by addyosmani** [comment]
> In the Backbone's Sync API section, the MyAPI example sets requestContent['resource'] to model.toJSON() but then doesn't do anything with it. Is something missing?

I think we should have extended the example further to demonstrate Sync API usage. The issue is that sync is supposed to be overridden. Perhaps we could cover an example a little more like this http://stackoverflow.com/questions/5096549/how-to-override-backbone-sync?

> Is the json2.js support needed for legacy browsers that don't support JSON, legacy servers, or both?

It's just required for legacy browsers afaik. I think we're actually safe dropping this if mentioned inline in text but it's okay to keep it in functional examples that people run in the browser.

> I take it that event.target is the recommended way of getting to the DOM element on which the event was triggered, but is there a way to get to the handling element that 'this' would have been bound to? Would this always end up being this.el?

To the best of my knowledge, yes, event.target is the best way of achieving this. this will always be this.el or this.$el depending on whether you are looking for a jQuery wrapped version of the element reference. If you have an example to accompany your question I could find out for sure!

**Comment by dcmaf** [comment]
@addyosmani Updates pushed to my branch.

I think there is a need for some discussion (and possibly diagrams) of the sequence of events that occur when using the RESTful API operations (e.g., what events get fired during a save(), fetch(), etc. and when, as well as what gets updated and when). I think it is too detailed to get into in Chapter 3, so I don't know where it would go. Is there anything like that already?

**Comment by addyosmani** [comment]
Would it make sense for that to be described in the practical that goes through REST? We could talk about the sequence there and I think it wouldn't be oddly placed. Thanks a lot for the changes made to your branch!

If you would like, I can merge the changes made so far and we can continue working on the updates to REST or alternatively keep this open until we've figured out a solution to the diagram/walkthrough

**Comment by dcmaf** [comment]
I'd say go ahead and merge these changes. I will continue reviewing chapters 4 and 5 and will be able to better answer your question after that. My thinking is that it might go before or after (more likely after) if not in the practical. I can open an issue to track the REST discussion.

**Comment by addyosmani** [comment]
Thank you so much. Merging this now!

**Pull request merged**
