### PR TITLE
A few edits

### PR DESCRIPTION
**Pull request by mdb**
Hopefully I'm not off-base in correcting what I perceived to be a few typos. Please let me know if I'm mistaken.

Also, I had some difficulty building the non-HTML versions. Assuming my revisions are acceptable, please let me know if you'd prefer that I take the time to build the other formats as well.

Thanks,
Mike

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the fixes @mdb! I'd be happy to merge these changes in. Could you rebase your PR against latest so that it can be automatically merged?

**Comment by mdb** [comment]
@addyosmani - No problem, I've rebased. Please let me know if further action is necessary.

**Comment by addyosmani** [comment]
Doh! It looks like one final rebase may be necessary. 

Do you think you might have time for it, @mdb? I hate to ask. If it's too much trouble I can manually cherry pick the changes against master but just wanted to double check in case you have bandwidth.

Really appreciate the PR once again!

**Comment by mdb** [comment]
@addyosmani - I've rebased again and hopefully resolved conflicts appropriately. Please let me know if there are further issues.

**Comment by addyosmani** [comment]
Was the mergability status green after the resolution? It's still saying there are merge conflicts on my end I'm afraid.

**Comment by mdb** [comment]
@addyosmani - I emailed you a few questions. Please let me know if you'd prefer this as the best place to discuss.

**Comment by addyosmani** [comment]
Thanks for the email! Basically I think what happened here was that there have been quite a few other pull requests trying to edit similar blocks you were and so those merges were forcing this PR to require rebases.

I've put a merge hold in place on the project until we sort out this PR. If you could follow http://learn.github.com/p/rebasing.html and resolve any last little merge conflicts then update your PR we should be good. Let me know if you need any help.

Thanks for following up!

**Comment by addyosmani** [comment]
@mdb Do you think you'll get a chance to update? We've had a few more PRs come through since and would be awesome to land this one soon. Really appreciate you helping out.

**Comment by mdb** [comment]
@addyosmani I should be able to take care of this at some point tomorrow. In the meantime, would you mind answering the questions I asked in my email? I'm familiar with rebasing, though not exactly clear on the aforementioned problems and could use a sanity check. 

Thanks!

**Comment by addyosmani** [comment]
Done :)

**Comment by addyosmani** [comment]
Great work, @mdb! Merging now. Thank you for your patience :)

**Pull request merged**
