### PR TITLE
update for todo app with Backbone.js 0.9.10

### PR DESCRIPTION
**Pull request by orizens**
updated backbone, underscore, localstorage, listeners.
the app gets a collection as a data source

### CODE REVIEW

**Comment by addyosmani** [comment]
Fantastic work @orizens! I really appreciate the work put into this. I'm going to pull this in but we may need to wait until further work to bring the rest of the book up to 0.9.10 is done. Sound good?

**Comment by addyosmani** [comment]
Adding to the list for #237

**Comment by orizens** [comment]
hi @addyosmani .
thanks for reviewing and updating.
does this mean that i have collaborated to the book?
may i review the other examples and suggest an updated code for latest backbone version?

**Comment by addyosmani** [comment]
@orizens, having reviewed your updated code I've decided..why don't we just make the whole book compatible with 0.9.10 and rock it? :) I think it would be amazing for the next version to match Backbone's latest release syntax and API wise.

I'm going to merge your changes to the book shortly. I would absolutely love for you to look at any other examples through the book you feel need updating to the latest version. That would help so much.

> does this mean that i have collaborated to the book?

Yes, you have!. Soon as this is merged. If you're able to help with the 0.9.10 updates to other parts of the book we may also be able to include you in the credits section at the intro to the physical version. Appreciate the help!

**Comment by orizens** [comment]
@addyosmani sounds great addy. I'll see what i can do regarding the other examples of the book.
I'm also working on my open source backbone app [Echoes](http://orizens.github.com/echoes/) and had proposals of writing a book on it.

**Comment by addyosmani** [comment]
Thank you! On Echoes, that's very interesting. I'm going to have to take a look through it this evening :)

**Comment by addyosmani** [comment]
@orizens do you think you might have a chance to identify what parts of the book might require updates to 0.9.10 so that we have a definitive list we can work to update?

**Comment by dcmaf** [comment]
Just a heads up - I am reviewing Chapter 4 (Exercise 1: Todos) and will have some changes to it to submit shortly. I did find that the code in the chapter results in some errors getting reported in the console when run with 0.9.10, so it will need to be updated as well.

**Comment by orizens** [comment]
hi @addyosmani, I'll try to let you know.

**Comment by addyosmani** [comment]
Thanks @orizens!

**Comment by addyosmani** [comment]
@dcmaf should we hold off on merging this in until we've updated the todos chapter with the newer example or do you think merging this should be a precursor?

**Comment by addyosmani** [comment]
Merging!

**Pull request merged**
