### PR TITLE
Chapter 3: Fixing error in validation section

### PR DESCRIPTION
**Pull request by americos**
Using .set() will not trigger the validation, using .save will

Here is a live sample of the code: http://jsfiddle.net/americos/vu8LD/

### CODE REVIEW

**Comment by dcmaf** [comment]
There is a difference between the .set in chapter 3 and that in your jsfiddle: the book version passes {validate: true} as a third argument to .set, which will trigger validation.

**Comment by americos** [comment]
Right, but the current code in chapter 3 does not passes {validate:true} this should be added.

**Comment by dcmaf** [comment]
The diff in your pull request https://github.com/addyosmani/backbone-fundamentals/pull/324/files indicates that the line changed contained `javascript myTodo.set('completed', true, {validate: true});`

Was your code above taken from the current content under chapters/ or from somewhere else?

**Comment by americos** [comment]
My bad. But it's Interesting though... I took the code from the current content in the gh-pages branch, but in the book link http://addyosmani.github.com/backbone-fundamentals/ I do not see that change, I actually get the code shown in the above screenshot.

Anyways thanks @dcmaf I'm closing this pull request since it's not an issue.

**Comment by dcmaf** [comment]
Yeah - the builds of the book are a bit behind the latest sources under chapters/. Probably best to read what is under chapters (or build your own version of the book). You may even want to keep an eye on the pending pull requests and open issues as there is quite a bit of movement going on lately.

**Pull request closed without merging**
