### PR TITLE
Chapter 4: "Exercise 1 Todos" - Updates

### PR DESCRIPTION
**Pull request by dcmaf**
Worked through the example using the code in the book and added additional
explanation and rewording.

Moved discussion of templates up to the HTML section so that all the HTML
is presented at once. This made it easier to follow what was going on with
the filters in the AppView since the hyperlinks are in the #stats-template.

Moving the templates up caused the two 'In Action' sectons to run together. It
also results in the UI being much more functional initially since the templates
are in place, so it makes less sense to be creating the first couple todos via
the console. I left that part in along with the associated screen shots.

I tested using Backbone 0.9.9. Errors occurred when attempting to use 0.9.10,
so the book example code and discussion will need to be updated when the example
is brought up to 0.9.10.

Is there a memory leak in TodoView? It seems like we are binding to events on the
model in initialize() and one binds destroy on the model directly to removal of
the view, which would seem to delete the view without unbinding the events. Elsewhere
we have said that this can result in memory leaks - or is it not a problem here since
the model has been destroyed? It looks like the latest version of the github TodoMVC
uses listenTo here.

Also fixed a missing '>' in a comment in chapter 3.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for looking into this! Just to check, do the issues above apply to #301? I'm happy to merge that now so that we can re-assess what is remaining to be done for that tutorial.

**Comment by dcmaf** [comment]
These changes are based on the chapter as-is; it looks like #301 updates the files in the practical but not the source within the chapter. Once #301 is integrated I could incorporate the updated source into the chapter and update the text as needed (or @orizens could do so as part of #301).

My thinking would be to go ahead and integrate this now and then bring the chapter up to 0.9.10 after #301 has been integrated (I could open an issue to do so).

**Comment by addyosmani** [comment]
Sounds great to me. Merging your changes right away!

**Comment by orizens** [comment]
hi @addyosmani .
are there new code examples needed to be updated?
if so - can you please tell me how to update my pull request code?
Thanks.

**Comment by addyosmani** [comment]
At the moment there are still some examples that could be updated to the latest version of Backbone. We'd love someone to look through the basics section, module loaders and two practicals just to make sure we didn't miss out on anything.

**Pull request merged**
