### PR TITLE
First commit of JQuery Mobile and Backbone codebase

### PR DESCRIPTION
**Pull request by raDiesle**
jqm and backbone:  first codebase, see https://github.com/addyosmani/backbone-fundamentals/issues/256#issuecomment-12009548

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for this! I haven't been able to get it running unfortunately. Testing your branch/PR:

```
GET http://localhost:34342/assets/css/bg.png 404 (File not found) localhost:15
GET http://localhost:34342/dist/debug/handlebars_packaged.js 404 
(File not found) require.js:1833
Uncaught Error: Script error
http://requirejs.org/docs/errors.html#scripterror require.js:175
Uncaught TypeError: Cannot read property 'singleTodo' of undefined 
```

**Comment by raDiesle** [comment]
Hi Addy,

I did some fix and slight changes to TodoMVC ( still some changes have to be applied),
 to better demonstrate handling situations of jQM.
It's a bbb project, so run e.g. to compile the handlebars templates+partials

bbb handlebars  
bbb server

Is it working?

**Comment by addyosmani** [comment]
I just updated to the latest bbb and ran `bbb handlebars` followed by `bbb server`. Output:

```
addyo at s0-0 in ~/projects/review-book-16/backbone-fundamentals/practicals/todoMVC_backbone_jqm-app on backbone_jqm*
$ bbb server
<FATAL> Unable to find "grunt.js" config file. Do you need any --help? </FATAL>

Running "server" task
Listening on http://127.0.0.1:8000
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
Error: ENOENT, stat 'assets/css/bg.png'
Error: ENOENT, stat 'dist/debug/handlebars_packaged.js'
```

Starting a new project via `bbb init` and doing a `bbb server` however does seem to work. I'm wondering if the example in the PR doesn't use the latest structure/have a grunt file?

**Comment by raDiesle** [comment]
Forgot to commit the grunt.js file :D .
I removed the example of the jquery validation plugin integration with backbone models.
Probably I should add a simple example to the validation chapter, because I think it's very useful.

There is still two bugs which have to be fixed. I'll continue on them after the chapter is in a good state.

**Comment by addyosmani** [comment]
Thank you for the update and no worries at all! I'm really glad it was just the missing grunt file and nothing else :) Looking forward to seeing how the rest of the chapter turns out. Quite a few devs looking forward to it.

**Comment by addyosmani** [comment]
Any further updates sir? :)

**Comment by raDiesle** [comment]
Ya, 
last weekend I spend time on coding on the TodoMVC example.
Should I commit it to the TodoMVC experimentals as well, what do you think?

Tomorrow I will tell friends to rewrite the chapter in nice English and ask for feedback,
as well as commit the chapter to Github,

What is the current state of the book?
How much time you expect to be left,
where I can improve the quality of the contents?

**Comment by addyosmani** [comment]
> Should I commit it to the TodoMVC experimentals as well, what do you think?

Yes, please do. We would be happy to consider a pull request :) That would rock.

> Tomorrow I will tell friends to rewrite the chapter in nice English and ask for feedback,

Awesome. That would be perfect.

> What is the current state of the book?

We are currently going under technical review and are actively working to improve all of the chapters, so there's still time to improve :) I think if we can wrap up everything in the next two-ish weeks we should be good :)

**Comment by addyosmani** [comment]
@raDiesle Thanks for the updates. Really appreciate them. It appears that your latest set of commits come with changes to files that we've recently updated. 

Is it possible to rebase against master and only submit the files that were changed? If you're short on time, I can do this for you but would prefer for you to get the commit credits.

**Comment by raDiesle** [comment]
Hm,
seems like my rebase to master and commit new files failed, right?
Should the pull request only contain one commit of my changes, instead?
Feel free to add the files by yourself!

Until the end of the week, my coleagues are done with refactoring the english grammer and corrections, which I will commit.

**Comment by addyosmani** [comment]
I would be happy to merge in the changes with English grammar corrections but yes, a pull request with just one commit of your changes would be fantastic. Basically, just want to avoid older files being introduced over the more recents updates made to other chapters. Thanks! :)

**Comment by addyosmani** [comment]
@raDiesle Just pinging to check how things are going. It looks like we've moved mobile applications into chapter 10 since your last PR, but it would be fantastic to get an update with the grammar corrections if you think thats available. Thanks once again for your awesome time on this.

**Comment by raDiesle** [comment]
Hi Addy,
First I did on my branch.
Second and improvements, the weekend next week, because I am on vacation.
Thanks
Am 05.03.2013 21:55 schrieb "Addy Osmani" notifications@github.com:

**Comment by addyosmani** [comment]
That sounds completely reasonable. Thanks, @raDiesle :) @dcmaf if you have some time to look at the general direction this work has been taking, I would love your thoughts (coming from it as a beginner) as to whether it fits inline with the rest of the book. This mobile chapter would be appearing later on, likely after the modular and extensions chapters.

**Comment by dcmaf** [comment]
@addyosmani I'll take a look at it - I think it is the only chapter I haven't reviewed yet, other than the Appendix. Is raDiesle:backbone_jqm the version I should be looking at, or is there a more recent version?

**Comment by addyosmani** [comment]
Thanks Marc! https://github.com/raDiesle/backbone-fundamentals/tree/backbone_jqm does indeed appear to be the latest branch. @raDiesle if you could confirm (whenever you get a chance) that would be much appreciated.

**Comment by dcmaf** [comment]
Some initial thoughts (keep in mind that I'm coming at this as a true novice with regards to jQuery Mobile):
- I think this is a very important subject. Since it is using technologies introduced throughout the book (Grunt, RequireJS), it fits well at the end.
- From the start, there seems to be a presumption that the reader is familiar with jQuery Mobile and its navigation model in particular. Minimally, this should be noted along with a reference to where the reader can find the information they will need in order to understand the discussion in this chapter. Preferably, since the subject is how to use Backbone with jQuery Mobile, the chapter should provide the necessary foundation without requiring the reader to gather it from other sources.
- An example in the discussion of the navigation conflict would be helpful - the explanation is a little too abstract to follow easily.
- Integrate more with the rest of the book; e.g., note that we are implementing a mobile variant of the same Todo application that we have seen throughout the book, note that we are using the Backbone Super extension discussed in Common Problems, etc.
- I feel like I am missing the big picture of how the control flow works in the mobile application (if different from the browser version). It may be because we are starting with Routers, rather than starting with models and views. Also, it may be because we are talking about pages, but haven't discussed what a "page" is in this context. I suspect this is a jQuery Mobile concept that is part of that needed foundation.
- There is a lot going on in the BasicView superclass that is specific to jQuery Mobile. This could really use a detailed discussion of what these methods are and what role they play.
- It might be easier to follow if you present the concrete view first, as this should be analogous to what the reader is familiar with from the earlier exercises, and then delve into how the superclass is used to make it work in the context of jQM.
- Add a note in the discussion of the template that 'whatis' is logging to the console (I think that is what it does). The book hasn't used Handlebars a lot in its examples, so any usage of it that is not intuitive should be explained.
- Intercept jQuery Mobile events example uses jQuery.live() which is deprecated as of jQuery 1.7 (or is this different for jQuery Mobile?)
- The fact that jQuery Mobile is, at least in part, a UI widget library akin to jQuery UI is not mentioned until the end. This should be part of that up-front discussion as it really helps explain what using Backbone and jQuery UI entails. In a sense, this also serves as an example of integrating Backbone with a widget library, though the focus seems to be primarily on dealing with the route-handling conflict.

**Comment by raDiesle** [comment]
Hi Marc,
I agree to most of your points and will work for them at weekend.

The to quick jump into jqm conflicts, I already realized.
But, my main goal was to only concentrate on important content, related to Backbone.
There are tons of resources/books about JQM + they change frequently from version to version.

But still, I will try to have a fluent and understandable entry point to JQM + Backbone.

Thank you a lot!

**Comment by dcmaf** [comment]
@raDiesle - I think a section early on to introduce jQuery Mobile and how it supports responsive web design through a widget set that adapts to the display device would help bridge the gap. Up to this point in the book, views have worked directly on the DOM, so this would set the stage for the focus of this chapter being on integration of Backbone with a widget framework.

Beyond a high-level introduction, a discussion of how JQM does routing, along with an example, would help set up  the existing discussion. Other than that, a few references to books and online resources for more information should suffice.

Overall, I think this chapter is very useful - not only with regard to mobile application development but also illustrating how Backbone can be integrated with other technologies in general.

**Comment by raDiesle** [comment]
Hi,

today I continued to apply your suggestions to add more information and to not jump in too fast.
I'll continue when there is time.

To get the latest, you should check:
https://github.com/raDiesle/backbone-fundamentals/blob/ChapterMobile/chapters/10-mobile-applications.md

So I'm going to make a new pull request with the other branch.
Thanks,

David

**Comment by dcmaf** [comment]
@raDiesle Great - I took a quick look at it and the new up-front content looks good; it will definitely help newbies (like me) better understand the context.

**Comment by addyosmani** [comment]
I'm really liking the work that's gone into https://github.com/raDiesle/backbone-fundamentals/blob/gh-pages/chapters/10-mobile-applications.md. Well done, @raDiesle and @dcmaf. I especially like that this chapter has tried to tie in some of the work that has gone into previous sections.

In it's current form, I would be happy for us to merge this in and iterate, but I'll ask: is there any (urgent) further work that needs to go into this? I noticed there's an outstanding TODO, but other than that it would be great to know what state this is in as we're going to try wrapping up the book this weekend.

Thanks once again all.

**Comment by raDiesle** [comment]
Hi,

I will finish my changes for additional explanations and nicer diagrams
 in 6 hours and rebase with gh-pages.

Can you close/reject  this pull request, because I deleted the repository
and it is not well rebased.

Instead, consider this pull request
https://github.com/addyosmani/backbone-fundamentals/pull/377

I will proceed with small optional corrections within the next days.

**Comment by addyosmani** [comment]
Thank you, @raDiesle. I would appreciate that greatly. I'll close up this PR now and we can focus on 377.

**Pull request closed without merging**
