### PR TITLE
Rewriting the Backbone, AMD and RequireJS section

### PR DESCRIPTION
**Pull request by jackfranklin**
As discussed in #233, I've been taking a look this evening at the RequireJS section.

Please be aware that this very much a massive WIP. It's not all done at all but I wanted to make the PR early so you could see it as it was taking place, and also provide feedback along the way. 

I've rewritten bits but a lot of it has been more reworking, or moving certain paragraphs around.

As I said, hugely a WIP but would love to see your thoughts. I'll continue working on this this evening and over the next couple of days. There's a lot I haven't done and the bits I have done I want to revisit too. You'll see I've got my little "TODO" list in the markdown too - I left that there to easily keep track, I'll obviously remove it once I think I'm fully done.

Thanks!

(Apologies for the large initial commit too - will be doing more frequent smaller commits from now on!)

### CODE REVIEW

**Comment by jackfranklin** [comment]
@addyosmani hey Addy, just done a bit more work on it. Not finished yet but did some on the config and shimming for libraries that don't support AMD out the box. As always, let me know your thoughts! :)

**Comment by addyosmani** [comment]
Fantastic work, @jackfranklin! I just added some minor comments but it's looking really great so far :)

**Comment by jackfranklin** [comment]
Hey Addy, have done some more tweaking and editing of the Require + Backbone and R.js bit. There wasn't much I wanted to change in the R.js bit, as it happened!

**Comment by addyosmani** [comment]
Awesome, Jack! It's looking great so far :)

**Comment by jackfranklin** [comment]
Thanks Addy! Is there anything silly that I've missed do you think?

When I next get a moment I'll do a bit of re-reading and probably tweak a couple of bits.

**Comment by addyosmani** [comment]
I don't think (for an introduction) you've really missed anything. @jrburke's RequireJS documentation is already fairly detailed and we ideally want to cover just the essentials. The next part would be discussing how to use RequireJS + r.js with Backbone with examples.

For that, you could probably use https://github.com/addyosmani/todomvc/tree/gh-pages/dependency-examples/backbone_require, which we've updated to work with latest Backbone recently too :)

Thanks once again!

**Comment by jackfranklin** [comment]
Great, I'll add a section into the R.js bit linking to that and explaining certain bits.

**Comment by addyosmani** [comment]
Hey Jack. How are things going? :)

We're going to do an update to the current online (and O'Reilly) versions of the book this week, just to give everyone a chance to look at the changes. If there's more work you'd like to go into that it would be awesome to get it in this week, otherwise more than happy to merge at a time that works for you.

This is really just an interim update so not too much worry!

**Comment by jackfranklin** [comment]
Hey Addy! 

Sorry for not updating - I hope I can get some stuff in tomorrow evening that you can then use? I'm away in France for a few days on Wednesday so wont be around then but will take another look tomorrow and push some more changes for you.

**Comment by addyosmani** [comment]
Thanks so much, Jack. That would be amazing :)

**Comment by jackfranklin** [comment]
@addyosmani didn't get time to do some tonight but will find time tomorrow during the day.

**Comment by addyosmani** [comment]
@jackfranklin No worries! Totally understand. Appreciate any time you get to spend on it during the week :)

**Comment by jackfranklin** [comment]
Hey Addy - did some more editing tonight. Not going to be able to do any more until early next week now so if you're happy for this to be merged in please do, or if you'd like more to be done just let me know and I'll take a look when I can :)

**Comment by addyosmani** [comment]
Thanks Jack! That's totally cool. I'll take a look at the edits you made this evening - sure they're great. Anything else you can put together next week would rock :)

**Comment by addyosmani** [comment]
Jack, I'd like to merge this in so the latest version of the book and continue over on https://github.com/addyosmani/backbone-fundamentals/issues/275 if that's cool. Fantastic work on updating this chapter so far. 

Please remember for the next PR to add your name to the start of the chapter so you get credit for it :)

**Pull request merged**
