### PR TITLE
Chapter 8: Modular Development - Minor corrections / rewording

### PR DESCRIPTION
**Pull request by dcmaf**
I've merged my changes with Mat's recent updates (hopefully cleanly!).

I'll open an issue later with my comments on this chapter. Let me know if you would prefer that I add them to Mat's issue #349 which pertains to this chapter.

Marc

### CODE REVIEW

**Comment by addyosmani** [comment]
Thank you for this, @dcmaf :) If you could add your comments to Mat's issue that would be fantastic. It's useful to track feedback from a smaller number of issues where possible.

**Comment by addyosmani** [comment]
@dcmaf I'm hoping to bring this and other changes back in shortly. One of the recent pull requests appear to have accidentally re-introduced older versions of the extensions chapter. I believe we need to remove 06-bbb.md, 07-extensions.md, 08-common-problems.md, 09-module-development.md. If you have time, could you verify?

**Comment by dcmaf** [comment]
@addyosmani I believe the files that need to be removed are 06-bbb.md, 07-extensions.md, 08-extensions.md, 08-common-problems.md, and 09-modular-development.md. In their place are 06-extensions.md, 07-common-problems.md, 08-modular-development.md, and 09-bbb.md.

I have added changes/corrections to chapters 11-13 (the unit testing chapters) to this pull request, along with a small correction in chapter 15. I will add my comments on those chapters to the issues previously opened by @wibblymat.

**Comment by addyosmani** [comment]
Thank you so much for checking. I greatly appreciate it and the additional updates you've made to this PR. Once I've removed the unnecessary files in master at the moment, I'll begin to land the latest PRs, starting with this one.

**Comment by addyosmani** [comment]
Thanks once again! Merging.

**Pull request merged**
