### PR TITLE
Fix typo in comment url.

### PR DESCRIPTION
**Pull request by ugisozols**

### CODE REVIEW

**Comment by addyosmani** [comment]
Thank you so much for these little fixes @ugisozols. We love consistency and keeping the book both clean and accurate so if there are any other things you notice I'd be happy to merge in fixes for them.

**Comment by ugisozols** [comment]
Sure, I'll keep contributing as I'm progressing through the book.

Btw, which way do you prefer:
- small commits in separate PR's
- one PR containing many commits

**Comment by addyosmani** [comment]
Whichever works better for you :) One PR with many commits also works

**Comment by ugisozols** [comment]
Alright, I think I'll stick with many small PR's because it allows me to easily edit single commits in case I screw something up.

**Pull request merged**
