### PR TITLE
Wordsmithing and punctuation fixes in chapter 1 and 2

### PR DESCRIPTION
**Pull request by dcmaf**
Addy - I have done some additional reworking of wording in chapter 1 and done the same in chapter 2. Please review (make sure your meaning hasn't been lost!) and consider incorporating.

Regarding chapter 2 (Fundamentals), as a reader I found it somewhat redundant to what is covered in chapter 1, though it goes into far greater detail. By the end of it, I felt like I had had the MVC pattern explained to me a half-dozen times, but had yet to see an example of Backbone in action. I found the Cranium example a little confusing, in that I was expecting an example showing Backbone (since it is the subject of the book). At this point as a reader I am also more interested in examples of how I would use a framework to implement models, views, and controllers than in how such a framework could be implemented. 

I can understand the rational for introducing a hypothetical framework at this point, since Backbone does not have a Controller component. However, that could perhaps be worked around by explaining how event handlers within the view play the controller role. My recommendation would be to pull the Cranium section out and perhaps replace it with a simple example of end-user backbone code - this would also dovetail well with the reference to the Todo example at the end of the chapter and set up the deeper dive into Backbone's features in the next chapter.

Marc

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for your work on this @dcmaf!.

I admit that some of my love for patterns may have got the better of me when I first started writing this book and perhaps there isn't as great a need for a complete section on MVC and the hypotetical framework include. Would you like to put together a rough draft of what you might replace the Cranium section with (e.g in a gist or PR) so I can see what direction that might lead the chapter in?

First and foremost I want readers to leave the book with a thorough understanding of Backbone and your suggestions are inline with that goal so we should definitely explore them.

I hope to review the changes made soon! Appreciate your time once again.

**Comment by dcmaf** [comment]
Addy,

It took me a few tries to get through the Fundamentals chapter; I kept getting bogged down in the Cranium details. My initial inclination was to recommend moving the entire chapter to an appendix (it looked like you recently moved the MVP section to one). When I went through it again last night it seemed that the Cranium section was the sticking point, and while I am familiar with MVC from working with it on the server side, many readers may be new to it so it seems worthwhile to discuss. I will take a shot at putting something together - what I’m thinking is to remove the Cranium source walkthrough and change the Cranium usage example to a Backbone example with the events object moving from the Controller to the View.

On a separate front, does anything in the book address using widgets within views? It seems that most of what I have seen so far involves the views directly working with DOM elements, often using templates to do so. On my current project my views contain a lot of relatively simple input widgets, such as combo boxes and date pickers, along with more complex grid and map widgets (guess which were the first Backbone views I had to write). After first putting the code for configuring the input widgets directly in my base view class I am now refactoring to create separate views for each widget. Thus, I was wondering if there was a pattern for working with widgets that require going through an API and if I had missed it in my research (and if it is covered in the book).

Marc

**Comment by addyosmani** [comment]
Hey Marc,

My hopes with Cranium were that once readers understood how to craft something similar to Backbone, their understand of it and its API would 'click' a little more easily. I also wanted them to realize rolling your own didn't offer that much advantage, but maybe in trying to do that the chapter was made unnecessarily complex.

If this is the case I think we do need to revisit how that section is presented. I'm not opposed to Cranium moving to the appendix. It could indeed fit there alongside the additional information about patterns, but I feel that we do need to explain MVC to front-end developers early on. If done right this could indeed just be done with Backbone itself. I'd love to see your take on it as I'm sure it could be written better.

Regarding widgets: we actually have a chapter on AuraJS (https://github.com/aurajs), the scalable widget-based architecture project I started on top of Backbone.js being written up at the moment that should cover some of what you discussed. It should be landing in the next few weeks.

**Comment by addyosmani** [comment]
Having reviewed your edits I am very happy to merge them. Thank you so much for improving the readability of these sections :)

**Pull request merged**
