### PR TITLE
PDFs can be built again!

### PR DESCRIPTION
**Pull request by stephenplusplus**
I always wondered why there were recently updated HTML, RTF, markdown, and epub files being committed, but no PDF! I cloned the repo and saw there were images whose filenames had an extra `.` in the path. pdflatex wasn't loving that, so I renamed the images to a more fitting title. That fixed the build, and bam! PDFs are back!

### CODE REVIEW

**Comment by addyosmani** [comment]
Aha! So that's what it was. You rock, sir. Thanks for the fix. I'm going to test this locally to make sure the rest of the builds are getting output okay but it should be good for a merge after.

**Comment by Meligy** [comment]
Thanks a lot for checking this. I just tried it locally and got this though:

```
mohamed@MeligyDev /cygdrive/h/code/lib/backbone-fundamentals
$ make pdf
awk 'FNR==1{print ""}{print}' chapters/*.md > 'backbone-fundamentals'.md
# You need `pdflatex`
# OS X: http://www.tug.org/mactex/
# Then find its path: find /usr/ -name "pdflatex"
# Then symlink it: ln -s /path/to/pdflatex /usr/local/bin
pandoc -s 'backbone-fundamentals'.md -o 'backbone-fundamentals'.pdf \
        --title-prefix 'Developing Backbone.js Applications' \
        --normalize \
        --smart \
        --toc
pandoc.exe: Error producing PDF from TeX source.
! LaTeX Error: Unknown graphics extension: .57.08-AM1.png.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.4230 ...een-Shot-2012-03-05-at-12.57.08-AM1.png}

Makefile:40: recipe for target `pdf' failed
make: *** [pdf] Error 43
```

**Comment by stephenplusplus** [comment]
Are you sure you have my version?

```
l.4230 ...een-Shot-2012-03-05-at-12.57.08-AM1.png}
```

tells me there's still lingering files on your side, which have been `git mv`'d on my copy of the branch.

To elaborate on the issue, I believe LaTeX gets confused with the `.`s in the `Screen-Shot` paths, such as `12.57.08-AM1.png`.  With my branch, I've renamed these files to only include letters, numbers, and hyphens.  This way, LaTeX knows it's dealing with .png files.

**Comment by stephenplusplus** [comment]
And @addyosmani, I think I might have to put that `"You rock, sir."` part on my resume. The real thanks go to you, for all you've shared with the community. :+1:

**Comment by Meligy** [comment]
Actually I was trying in `master`. Now I see `gh-pages` has an updated PDF already.

**Comment by addyosmani** [comment]
@stephenplusplus could you rebase this PR? Sorry to ask, but there have been one or two changes merged since.

**Comment by stephenplusplus** [comment]
Should be all set now. I rebased and re-built the various formats.

**Comment by addyosmani** [comment]
Excellent work. Merging now. Thank you!

**Comment by Meligy** [comment]
Thanks a million, now I can build PDF again (on branch `gh-pages`) :) :+1:

**Pull request merged**
