### PR TITLE
Add Lumbar and Thorax chapters

### PR DESCRIPTION
**Pull request by eastridge**
This pull requests adds chapters for [Lumbar](http://walmartlabs.github.com/lumbar) and [Thorax](http://walmartlabs.github.com/thorax) in addition to adding a note about appending views.

### CODE REVIEW

**Comment by addyosmani** [comment]
So happy to see this here. Thanks for all of the time you spent on it @eastridge :) I'll review asap!

**Comment by addyosmani** [comment]
@eastridge Nice work! I just read through it. Is it possible for us to include a final paragraph/section to the chapter with say, links to the relevant complete Todo application so that developers can go take a look at it? Happy to merge otherwise.

**Comment by eastridge** [comment]
@addyosmani thanks, a closing chapter is a good idea. I'll write something up and include a few links including to the TodoMVC app.

**Comment by addyosmani** [comment]
@eastridge I would absolutely love to merge this in this weekend. Do you think you'll have time to wrap up the final part sometime soon? :)

**Comment by eastridge** [comment]
@addyosmani will push another commit with a closing chapter this weekend.

**Comment by eastridge** [comment]
@addyosmani so I added a little todo blurb, but I can't figure out a decent way to actually close things up. Feel free to edit and amend with prose as you see fit.

**Comment by addyosmani** [comment]
Thanks @eastridge. I appreciate the additions. We might consider expanding the closing with a little more sample code from the application, but otherwise it looks great. 

Awesome work on this chapter :) Landing now!

**Pull request merged**
