### PR TITLE
Code consistency

### PR DESCRIPTION
**Pull request by stephenplusplus**
Hey Addy,

This is a first-pass on a clean up of the code examples. I'm working on creating a consistent style, as far as...
- `function(){`, `function() {`, `function ( ) {` **->** `function () {`
- `function ( e, thing ) {` **->** `function (e, thing) {`
- `({example: 'here'})` **->** `({ example: 'here' })`
- `/* comments.... */` **->** `// comments.`
- 2 spaces
- various other clean up.

I created an .editorconfig file as well to help contributors.

I'm sure there are some things I've missed, and there are definitely other areas that need attention as well. Let me know if you're interested in going down this road, and I'll keep plucking them out :facepunch:

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@addyosmani This is obviously a huge change to look over. If I submitted chapters individually, would that make it easier to review?

**Comment by addyosmani** [comment]
@stephenplusplus I think it's actually perfectly okay in it's current form but would need to be rebased - thanks for taking the time to put this together! :)

The only reason I haven't been more active in reviewing this is that we're going through the last rounds of review before the O'Reilly first edition publish this week. If you can rebase, I'll review this weekend.

**Comment by stephenplusplus** [comment]
Cool, happy to!

**Comment by stephenplusplus** [comment]
@addyosmani I started to rebase, but looking over the changes in the last 10 days, there were several conflicts. I think it's best that I start over, which I'm more than happy to do. Can you let me know when a quiet block of time is to start, before merging in any other changes? I know a higher priority is on the actual content of the book, especially now that you're in crunch time, so I don't want to cause any unnecessary noise and confusion. So whenever you think is best, it shouldn't take me more than a couple hours to do at least an initial sweep. I just want to avoid going off in separate directions, making it harder for everyone. Thanks!

**Comment by addyosmani** [comment]
Hey @stephenplusplus! Thank you so much for volunteering to help with code consistency. I would say that if we gave it a week or two (perhaps starting at the end of May) we'd be in a good position to start getting consistent with the examples. I'd love for us to be able to tackle this (if possible) by introducing a style guide and then getting PRs together on a chapter-by-chapter basis. That way I think we can more easily track down any changes which break the style guide as we're updating them. Thanks again for your time!

**Comment by stephenplusplus** [comment]
Sounds good to me! I'll get a style guide together soon, and see what you think!

**Comment by stephenplusplus** [comment]
@addyosmani I changed the PR to one commit which updates the readme, and includes a codestyle.md file. If you prefer other rules, let me know! It's mostly the guide as is [from TodoMVC](https://github.com/tastejs/todomvc/blob/gh-pages/codestyle.md).

**Pull request closed without merging**
