### PR TITLE
Chapter 5 rewrite (#286)

### PR DESCRIPTION
**Pull request by wibblymat**
I've removed a lot of detail that simply wasn't necessary because the material was already covered in chapters 3 and 4.

I also went through the source code attached to the original tutorial and made a lot of style changes to make it look like example code elsewhere in the book.

It's quite a big diff in the end. Hopefully I've made things clearer and less obviously transplanted.

### CODE REVIEW

**Comment by wibblymat** [comment]
Hmm, some of the screenshots are no longer quite right for what the sample code actually does at each point. They probably should all be re-done.

There aren't that many screenshots elsewhere in the book that show window decoration, but the ones that do are taken on a Mac. I don't have access to one, so for the sake of consistency we might want someone else to do them (or Photoshop OSX window decoration over my Ubuntu screenshots :D)

**Comment by addyosmani** [comment]
@wibblymat first, thank you so much for your epic work on this. In case I haven't asked, would you like to be a tech reviewer on the book? If so, I can get you in touch with O'Reilly.

On the PR itself: would it be possible for you to take screenshots on Ubuntu of the in-browser window? I've been meaning to do this for the other screenshots and hope to re-take them after our first tech reviewers for the book are wrapped up. Consistency would be awesome.

**Comment by wibblymat** [comment]
I'd be happy to be a tech reviewer for the book, just let me know what
needs doing!

I'll work through the exercise again and take screenshots probably tomorrow.

**Comment by addyosmani** [comment]
I just read through the markdown preview. It looks good :v: 

Have you tested the updated tutorial steps work? :) I'm going to verify they still do and we should then be good for a merge. Will let you know if I have any other feedback tomorrow!

**Comment by addyosmani** [comment]
@wibblymat could you email me? Will get the process started :)

**Comment by wibblymat** [comment]
I have done a run through, but will do another while taking screenshots.

**Comment by addyosmani** [comment]
Thanks Mat! That sounds fantastic.

**Comment by addyosmani** [comment]
@wibblymat your revised changes look great for a merge. Is there anything more you would like to do for this PR before it gets landed? Anything we might need to update to Backbone 0.9.10?

**Comment by wibblymat** [comment]
The only change I was going to make now was to update the screenshots which could be done as a separate PR if you want to merge.

I used 0.9.10 when testing the example code so everything should be fine in that respect.

Reviewing the book at the moment, so was intending to take screenshots when I get to this chapter since I'll be checking the examples anyway.

**Comment by dcmaf** [comment]
@wibblymat if you are reviewing chapter 3 you may want to look at the pending changes on my branch and the comments on the associated pull request so that we are not duplicating effort. I will do the same with your changes when I get to chapter 5.

Marc

**Comment by wibblymat** [comment]
@dcmaf Will do, thanks for the heads up!

**Comment by addyosmani** [comment]
@wibblymat thanks so much for the update. I'm happy to wait on the screenshots in the same PR and it's great to hear that you've been testing 0.9.10 for the code samples as you've been adjusting them. I really appreciate you and @dcmaf syncing (you're both tech reviewers). Your help is really helping improve this book.

**Comment by dcmaf** [comment]
@wibblymat - FYI, I just put in a pull request with changes to Chapter 4. Primarily, I added more detail to the explanations of what is going on, but no changes to the underlying code.

**Comment by addyosmani** [comment]
So the PR referred to above by @dcmaf has been merged. Happy to merge this one too once you're happy with it, Mat :)

**Comment by wibblymat** [comment]
I am finally redoing the screenshots now, so this should be good to go later today. Hopefully the delay hasn't caused any difficulty!

**Comment by addyosmani** [comment]
That is fantastic. Thank you, Mat!

**Comment by wibblymat** [comment]
Finally! Had to redo all of the ones I'd taken yesterday because there was a swear word in the title of one of my other open tabs. Oops!

**Comment by addyosmani** [comment]
Whoops! I really appreciate the effort Mat. This should hopefully be good to land soon!

**Comment by addyosmani** [comment]
The screenshots look fantastic. Thanks so much for all your work updating this, Mat. Merging now!

//cc @dcmaf

**Pull request merged**
