### PR TITLE
Replacement of Cranium section in Fundamentals + Chapter Overviews in Introduction

### PR DESCRIPTION
**Pull request by dcmaf**
Added descriptions of the content of each chapter to the end of chapter 1.
Replaced Cranium section of chapter 2 with an example and discussion of how Backbone implements MVC pattern.
Additional wordsmithing and corrections (primarily in chapter 2)

Addy - Here is my proposed replacement to the Cranium section in chapter 2. I tried to borrow from the Todo example to show how Backbone relates to MVC without getting into too much detail about Backbone itself. I also re-worked some of the earlier sections of the chapter to improve flow. I feel like the much of the Implementation Specifics section is redundant with what has been said elsewhere and other parts of it may fit better elsewhere in the book since the chapter is so MVC-focused, but I left it as-is other than some tweaks to make it consistent with the new example.

I also added chapter descriptions at the end of chapter 1. Even though you end the chapter with an overview of what the book covers I felt like it was missing this deeper level and is something I have come to expect in technical books. You should definitely look at these as (having not actually read beyond chapter 3) I may have missed the gist of some of the chapters (I'm not even sure I have all the chapter breaks correct!).

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for working on this, @dcmaf! I'm going to read through the edits you've made this evening and will hopefully get back with some feedback or a merge tomorrow. 

We may want to move Cranium into the appendix, but I'll look through the replacement first to see if it does a good job of walking readers through with something similar. Thanks again!

**Comment by addyosmani** [comment]
I've reviewed the suggested changes and on the whole I really like them. I do still think however that we should move Cranium into a standalone page in the appendix, just as a sort-of 'Hey, here's how you might implement your own minimalist Backbone in case you were wondering' kind of thing.

How does that sound to you? Maybe we also add a callout at the end of the rewritten section to let readers know they can learn about that in the appendix if interested. I think it would tie everything together quite nicely. 

Finally...

How would you feel about becoming an official technical reviewer for the book? :) You've been doing such a great job with your edits so far that having you involved in that capacity would be fantastic. You would also get a credit in the first few pages of the book. If that sounds good to you, could you drop me a quick email saying you're interested so I can forward it to the publisher?

**Comment by dcmaf** [comment]
Thanks Addy,  I'm glad you liked the changes. I think the Cranium would work well at the end as an advanced section; definitely nice to see how such a framework works under the covers.

I would be interested in being a technical reviewer, what is the process and timeline with the publisher? Also, keep in mind that I am relatively new to client-side programming, Backbone, and JavaScript. Until recently I had been doing purely server side work in Java/Spring, so I'm probably stronger on design patterns and weaker on client-side development issues than your typical reader.

**Comment by addyosmani** [comment]
@dcmaf I think that's actually of benefit to the review process. Many of the other tech reviewers we're going to work with are used to using Backbone and can help with code errors and fact checking. An equally important challenge is ensuring that to someone new to this arena, the flow and explanations in the book are as clear as possible. Your input I feel would greatly help us on that front.

The timeline at the moment is: begin the review process next week - this typically takes a few weeks on its own. We're then given a few weeks to make the necessary edits and adjustments to address feedback and hand the book in to the publisher. O'Reilly are an on-demand publisher so we can still make edits beyond that point, they would just be delayed. That doesn't however affect how early we can release them in the open-source version.

How does that sound?

If you get a chance, could you update your PR to move Cranium to the appendix? :)

**Comment by dcmaf** [comment]
Sounds good Addy.

What is the process for the review period - will I be working with the publisher reviewing specific draft versions or will it be similar to what we are doing currently?

**Comment by addyosmani** [comment]
More or less what we're doing currently. Could you drop me an email so our
publisher can get in touch? :)

**Comment by addyosmani** [comment]
@dcmaf Done! You should hopefully hear from them in the next few days. 

If you get a chance, do you think you could update a92bfe0 so that Cranium is in the appendix? :)

**Comment by addyosmani** [comment]
Thanks for your time on this once again! I manually resolved the merge conflicts using a cherry pick and brought them back into the book. Also brought in the changes you emailed and resolved the conflicts there. They're all in master now :)

**Comment by dcmaf** [comment]
Great, thanks for dealing with the merge!

Marc

**Pull request closed without merging**
