### PR TITLE
Update 04-exercise-1.md

### PR DESCRIPTION
**Pull request by johanneslumpe**
Added window in front of two calls to match the explanation.

### CODE REVIEW

**Comment by addyosmani** [comment]
Thanks for the PR. Could you rebase against master?

**Comment by johanneslumpe** [comment]
I'm new to git - not sure how to do this. If you show me, I'll know it for future PRs!

**Comment by addyosmani** [comment]
Sure thing! here are some guides:
- http://learn.github.com/p/rebasing.html
- https://help.github.com/articles/interactive-rebase
- http://git-scm.com/book/en/Git-Branching-Rebasing

**Comment by johanneslumpe** [comment]
Ok, tried it very quickly. Got to checkout the branch and also a rebase seemed to work fine. When i tried it a second time git replied "Current  branch head is up to date". But I don't know what do to now... Sorry ,that this is taking so long, I will read more tutorials on Git so that I can do this better in the future.

**Comment by addyosmani** [comment]
No worries at all. Thanks for taking the time out! If you need help I'm happy to bring these changes in manually.

**Comment by johanneslumpe** [comment]
Ok I tried a bit more - got as far as to switch the branch properly and do the rebase - but it detects two merge conflicts. So before I break anything it might be better to update this stuff manually - sorry :/

**Pull request closed without merging**
