### PR TITLE
using _.bindAll since 0.5.2 is IMHO deprecated.

### PR DESCRIPTION
**Pull request by OpenGrid**
Documentation suggest adding context as a third parameter to bind. I also noticed that _.bindAll is less clear to newcomers.

### CODE REVIEW

**Comment by addyosmani** [comment]
For reference on this ticket:

As of Backbone 0.5.2, it's no longer necessary to use _.bindAll(this...) in your views to set the context of the "bind" callback functions, as you can now pass a 3rd argument to bind() that will set the context (i.e. "this") of the callback.

For example:

<pre>
var MyView = Backbone.View.extend({
  initialize: function(){
    this.model.bind('change', this.render, this);
  },
  render: function(){
    // "this" is correctly set to the instance of MyView
  }
});
</pre>

**Comment by addyosmani** [comment]
@OpenGrid I agree this change should be made. Would you like to update other instances of _.bindAll() as a part of this PR? If you don't think you'll have time, happy to do it myself at a later point.

**Comment by OpenGrid** [comment]
There are only two instances of bindAll in readme.md all changed in my patch. Did you mean updating practicals?

**Comment by addyosmani** [comment]
@OpenGrid I did indeed. I've just merged this patch but if you have time/are up for it, it would be great to get the practicals updated too. Again, happy to do these myself.

**Pull request merged**
