### PR TITLE
Replacing term "hashtag" with "hash mark" to prevent spread of misinformation

### PR DESCRIPTION
**Pull request by ghost**
According to RFC 3986, the identifier following the number sign ("#") character is called a fragment identifier. Hashtag is a microblogging concept, and the terms should not be used interchangeably when referring to the structure of a URI.

Proper usage of hashtag, e.g. "Thanks for recently favoriting my hashtag-less tweet talking up this book."

### CODE REVIEW

**Comment by addyosmani** [comment]
Well spotted. This should definitely not be hashtag - could you let me know what you think of the comment on the change? I would be happy to merge otherwise (and thanks for the PR!)

**Comment by ghost** [comment]
My pleasure. And thanks for getting back so quickly. Wasn't sure exactly what you were looking for, so I made a slight change to add additional clarification in a new commit. Hopefully that helps users understand what they're looking at in the examples already in place in the book.

**Comment by addyosmani** [comment]
@jhabdas I appreciate your changes here. It appears that this PR can't be merged at the moment but it would be fantastic if you could rebase. I think the clarification is perfect as is.

**Comment by addyosmani** [comment]
Thanks again! I've manually brought this in as I was working on the same files today.

**Comment by ghost** [comment]
Thanks for pulling in my changes, Addy. My feeble attempt to rebase last week ended up pulling in a bunch of unrelated commits, and so I had to do some history rewriting to keep this branch clean. Looking forward to continuing through the book.

**Pull request closed without merging**
