### PR TITLE
enhanced collection example

### PR DESCRIPTION
**Pull request by gschema**
Hi @addyosmani,
I've changed code example to be consisten with previous examples and extended example to show concreat add() in action as it is implicitly called out just before, so expected imo and experience reading it.

Also, I think it would be better to use Photo model instead of Backbone.Model as it could be confusing, even though a type of Backbone.Model is expected. Errors are thrown in case not all defaults of the expected Model type (in this case Photo) have counterparts in passed object to Backbone.Model when instantiating it and later those counterparts being used in app.

Should that be avoided, in general?

Cheers,
Dusan

### CODE REVIEW

**Comment by addyosmani** [comment]
> Also, I think it would be better to use Photo model instead of Backbone.Model as it could be confusing, even though a type of Backbone.Model is expected

I fully agree with this.

In case you're interested/would like to help: one of the items on my todo list is to rewrite the examples in the basics section to better fall in line with the Todo application we create in the first practical. It might be that we end up using code samples from the tutorial directly or simply model Todo concepts instead of the photo gallery.

My thinking is that this would give them a nice Aha! moment when it comes to the tutorial and everything finally fits together. 

What do you think? It also might fit in well with my thoughts about iterating on the Todo app throughout the book. e.g we're working on a Backbone.Marionette section for next week and that will show people how to take the first practicals Todo app and rewrite it to follow Marionettes pieces/best practices.

**Comment by gschema** [comment]
I think it would be great, I'd like to participate.

Do you have some more info on this or should I start with above ideas and iterate, if needed, through pull requests?

**Comment by addyosmani** [comment]
@g6scheme That would be awesome :)

Was thinking we could:
- Use http://addyosmani.github.com/backbone-fundamentals/#practicaltodos as a starting point then take a look at
- http://williambrownstreet.net/work/backbonejs.slides/codemirror/introduction/index.html#sample-app
- http://wekeroad.com/2011/08/11/the-backbonejs-todo-list-sample-refactored-part-1/
- and  http://courseware.codeschool.com/The_Anatomy_of_BackboneJS.pdf

for further reference. I feel like it might just take a few short hours to redo the examples and they might even work standalone with the console.

**Comment by gschema** [comment]
@addyosmani Cool, I will get down to this asap.

**Comment by addyosmani** [comment]
@g6scheme Thank you very much for your recent PR to help improve the first Practicals section :) I'm not sure how much you might be interested in helping out with the book, but if you'd be up for it, I'd be happy to give you a thank you credit in the opening chapter/book info section.

Right now there are a few key areas that I would really love to make better:
- In 'The Internals', as discussed earlier, I'd love to replace those examples with Todo app examples which provide a better example flow.
- In sections like Modular development and Mobile, I feel like there are flow issues where the content could read better or lead on from one topic to another more smoothly.

I'm very much working on improving the book at the moment myself, but moreso focusing on new content. You might have noticed over the past few weeks the addition of the practicals, Backbone Boilerplate, Backbone.Marionette, and the tips and tricks chapters. Any help improving the existing content would be amazing and would allow both new and current content to be as solid as possible.

I'd also of course be happy to send you a physical copy of the book whenever the book gets finished :)

**Comment by gschema** [comment]
@addyosmani 

I really enjoy working on this and I am going to keep contributing (this deepens my knowledge and understanding of the matter and I like teaching, to tell you the truth, and this is kind of it).

I am going to tackle "examples in the basics section" next for which you gave me enough ideas and references for. 
Do you have ideas and refs for the Modular dev and the Mobile section?

Also, thank you very much, I am really flattered for the credit and physical book proposal, that would be fantastic.

**Pull request merged**
