### PR TITLE
Fixed typo under "What is 'el'?"

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Added the function skeleton for switchContext and removed // etc.  Since this was the only item missing, it seems clearer to just include it.

**Comment by ghost** [comment]
I don't understand the point of Option 2 and how it might be different from Option 3, under Object Literals.

**Comment by addyosmani** [comment]
@terryroe Reviewing the code atm I don't see a functional difference between 2 and 3 either. I'll try digging up my notes but if I'm unable to find a reason, I think we should just strip Option 2 completely.

**Comment by ghost** [comment]
@addyosmani I think removing Option 2 is the correct thing to do.

**Comment by addyosmani** [comment]
@terryroe This should be the case in the current version in master at the moment. Cheers!

**Pull request merged**
