### PR TITLE
Section: Optimize and Build a Backbone.js JavaScript application with Require.JS using Packages

### PR DESCRIPTION
**Pull request by pixelhandler**
Addy, 

We exchanged emails on this topic, I added a new section which follows "Build profile to optimize all dependencies required in app.js inside the `appDir`" 

The new section: "Optimize and Build a Backbone.js JavaScript application with Require.JS using Packages" ... is based on an application that is currently under development for a mobile site.

Best regards,

-Bill Heaton

### CODE REVIEW

**Comment by addyosmani** [comment]
@pixelhandler Just wanted to say thanks for this once again. I haven't forgotten about it and will be re-reviewing and merging once I've had a chance to do some spring cleaning on the Backbone/RequireJS section of the book.

**Comment by addyosmani** [comment]
@pixelhandler I just made a comment regarding markdown and html which you should probably ignore (I only just realized re-reviewing this PR that you included both versions!) :)

**Comment by addyosmani** [comment]
There's some very minor typos in this but other than that it looks good. I'll be working on the book some more this weekend so hopefully I'll be able to finally merge. Thanks for your patience!

**Comment by pixelhandler** [comment]
Addy, I removed the extra files and the typos should already be address in a previous commit - https://github.com/pixelhandler/backbone-fundamentals/commit/2b88f46a8b13aed65d77e86d02f5ba2804efcc92

-Bill

**Comment by addyosmani** [comment]
I believe I left a comment about this on the actual pull, but I finally brought this content in. Thanks again!

**Pull request closed without merging**
