### PR TITLE
Use xelatex instead of pdflatex to handle all the unicode characters

### PR DESCRIPTION
**Pull request by trtg**
Not sure if texlive on Macs is configured differently, but I'm running linux and specifying xelatex as the latex engine is necessary to avoid error messages related to inputenc and unicode when generating PDF output.

### CODE REVIEW

**Comment by tkalfigo** [comment]
I don't know if xelatex would solve the linux problem, but I confirm that pdflatex does indeed cause errors.

**Comment by addyosmani** [comment]
Thanks for the PR. I'm happy to merge this in if we can ensure that texlive works on Mac (and if possible Windows) as well. We currently require a PDF solution that works cross-platform if possible.

**Comment by Foxandxss** [comment]
I tried to create a PDF on os x with pdflatex and I had problems of unicode characters.

I confirm that this pull works on os x ML.

**Comment by tkalfigo** [comment]
On linux the solution is xelatex as described. I confirm it works fine.

**Comment by pierregoudjo** [comment]
@tkalfigo +1.

**Pull request closed without merging**
