### PR TITLE
Added an example of using require.js's syntactic sugar for use when defining modules.

### PR DESCRIPTION
**Pull request by meirish**
I prefer this way of using define as it feels more natural and "JavaScripty", but am hesitant to change all examples of `define()` to this as I don't think it's the more widely-used syntax. Also, I'm not sure about the placement of the change - it might make more sense after the discussion of `require()`.

### CODE REVIEW

**Comment by addyosmani** [comment]
@aaronmcadam @meirish I've seen James mention this alternative syntax on another repo and I definitely think it's worth including. As Aaron mentioned, perhaps we should consider adding it directly after the first define example with the tag 'Alternative syntax' and a one-liner to explain how it differs and why people may prefer it.

**Comment by meirish** [comment]
Cool - I added the heading. I like the sugared syntax better as it's also easier to add or remove dependencies - you don't have to count through the deps array and then the function arguments to make sure you're adding or removing the right one. Awesome to see a guide like this (and thanks for all of the awesome stuff you post on a regular basis)!

**Comment by burin** [comment]
I didn't know about this alternate way of defining modules. It's definitely handy! Keeping the dependencies array and the argument list synced has been a pain for me, and I've had it bite me a couple times :) 

The only thing that stood out to me is that `define()` and `require()` look similar if you don't use the sugared syntax, but once you use the alternate syntax, they are quite different. The question then becomes "can I use this kind of syntax for `require()` as well?"

**Comment by addyosmani** [comment]
@meirish merged. Thanks again!

**Pull request merged**
