### PR TITLE
Converting photo examples to todo ones

### PR DESCRIPTION
**Pull request by gschema**
Hi @addyosmani,
I just converted first two examples in the book from photo to todo examples.

I think this is what you have thought of. If you find me being on the wrong path hint me further.

Best,
Dusan

Reference:
[Spec](https://github.com/addyosmani/backbone-fundamentals/pull/173) :)

### CODE REVIEW

**Comment by addyosmani** [comment]
This is _exactly_ what I had in mind. Thank you so much @g6scheme :)

Do you think you might have time to work through the rest of the basics section? I've love to merge the rest of the work on this at once, but if you think you wont have time can do it in pieces.

**Comment by gschema** [comment]
Hey @addyosmani, you are welcome. :)

I'll cover the whole basics section asap (shouldn't take to long), so, yeah, it would make sense you to do bulk merge once whole section is done. I thought it would be good you to check this out before I continue, to be on the right course early on.

Afterwards, I'll dive "In sections like Modular development and Mobile" you've mention earlier if that is still to be improved. But, we'll catch on this once basics section is done.

Do you have some time schedule/constraints for the book?

**Comment by addyosmani** [comment]
Hey @g6scheme! I was hoping to get the book wrapped up in the next month. If you have a chance to work further on the examples conversion that would be absolutely fantastic. I can try to rework the modular + mobile section or write down some notes on how we can take that to the next level if you're interested. 

Do you think for consistency that that section should also build a mobile Todo app or should we stick with the photo gallery idea?

**Comment by anthonybrown** [comment]
Photo Gallery Please :)

**Comment by gschema** [comment]
@addyosmani I just returned from the vacation I took after the Fronteers conf. I will speed things up now. 

You can leave me the notes for rework of the modular + mobile section so you could work on other stuff.

Regarding Todo or Photo gallery I would say that basic section and the first practical wraps up quite nicely todo app as an example, so photo gallery app would make sense.

Anyway, I guess it would be better to reiterate with you on this once I dive into that section.

**Comment by addyosmani** [comment]
For modular + mobile, I'm considering rewriting the application as the first one was written some time ago and will try to include a few more best practices this time around. Will send over some notes as soon as this is ready! Do you think you'll have a chance to look at reworking some more of the examples this weekend? :)

**Comment by gschema** [comment]
Hey @addyosmani,
I will send you complete rework by Thursday and the rest (mobile + modular) could be done within week or two afterwards.

Best,
Dusan

PS I've had unusually to many staff going on at once during last month and a half and it is going to an end this weekend. Sorry if it took longer than expected.

**Comment by addyosmani** [comment]
Hey Dusan,

That sounds fantastic. I completely understand things getting busy. No
worries! I think if we're able to get some progress over the next 2-3 weeks
it won't take too much to get to the finish line on this book. Appreciate
your help a lot! :)

Cheers!
Addy

**Comment by gschema** [comment]
Hey @addyosmani,
I think this is ready for a review. I'll go through it once again over the weekend to brush it up. If you have tips, suggestions you are welcome. :)

Also, I have an idea/question.

From the very start ("MVC As We Know It" section) examples start with Backbone examples, but then the view example is presented as if we are doing/covering custom JS MVC implementation sort of. It feels to me that either it should be the Backbone example or everything else should be like custom MVC implementation.

I think it would be awesome if examples in the section at start covering MVC history and theory are done like basic custom MVC implementation for the purpose of illustrating how MVC behind Backbone works and basic structure behind the Backbone. It seems appropriate regarding the surrounding MVC theory, and would add great insight and value to the readers.

What do you think?

Best,
Dusan

**Comment by addyosmani** [comment]
Hi @g6scheme.

Thank you for the incredible work on rewriting the examples :) You've done an amazing job. I'm going to spend time reviewing the changes in more detail shortly. 

About your idea: I like it. I've always felt that including Backbone earlier on in the MVC As We Know It section seemed a little clunky and maintaining consistency there with how we present the examples makes a great deal of sense. I also think it would be great if the examples were done using a custom MVC implementation. 

For those, if we wanted we could continue sticking to the theme we'd already been using or I can pull out one of the custom "MVC" variations from TodoMVC that try to stick to vanilla JavaScript. There is of course also the mini framework I showed at the workshop but perhaps it's better for us to stay as minimal as possible for readability :)

Let me know if I can help out further in any way!

Btw, if you get a chance to rebase this PR (currently has some merge conflicts) that would be amazing!

Thank you!
Addy

**Comment by gschema** [comment]
Hi @addyosmani,
thank you. :)

I've done the rebase. It should merged with no conflicts now (which were very uncommon due to my workflow; pulling upstream often to avoid funky conflict/merging situations).

About vanilla MVC example:
I thought about the MVC from the workshop as well. My idea was it to be used for explanation of basic flows and patterns behind the MVC as it is hard to find one around the net. Also, I thought not to get loose to much as still it is the Backbone Fundamentals book. :)
Do you think that would work?

Best,
Dusan

**Comment by addyosmani** [comment]
Thank you so much for doing the rebase :) 

> I thought about the MVC from the workshop as well. My idea was it to be used for explanation of basic flows and patterns behind the MVC as it is hard to find one around the net. Also, I thought not to get loose to much as still it is the Backbone Fundamentals book. :)

Yes! I think it would :)

Going to merge this work now. Lets continue in further pull requests.

**Pull request merged**
