### PR TITLE
The "What is `EL`?" section updates

### PR DESCRIPTION
**Pull request by topliceanu**
The `el` property of a View is very important to the whole mechanics of Backbone. It should be clear how a View is attached to an existing DOMElement or how a View can create a new DOMElement to render it's contents in. 
I hope i have done that with this commit

### CODE REVIEW

**Comment by addyosmani** [comment]
@topliceanu As @sarxos mentioned there were a few minor errors you might want to change in this commit. You could do this by updating your fork and then clicking 'pull request' again which will allow you to update the commit range. If you're unsure of how to do this, let me know and I'll make these changes manually. Thanks!

**Comment by topliceanu** [comment]
I'm doing an "Update Commit Range"  on this commit https://github.com/topliceanu/backbone-fundamentals/commit/4a997a43e2de042682630c74593d4c7f6a6e4fe3 but i get neither a success nor a failure message from github.
I would really like to help, but if it's easier for you to make the changes manually it's ok

**Comment by addyosmani** [comment]
@topliceanu that's okay. I'll make the change and reference this ticket. GH sometimes likes being a pain :)

**Comment by topliceanu** [comment]
:) thanks addy

**Pull request merged**
