### PR TITLE
Prepared updated version of book in all formats

### PR DESCRIPTION
**Pull request by 1st**
As discussed here #597 I prepared new version of book in all formats.

### CODE REVIEW

**Comment by 1st** [comment]
Please merge it as soon as possible, before someone else will change book source :-) Thanks @addyosmani

**Comment by 1st** [comment]
@addyosmani please merge it

**Comment by addyosmani** [comment]
Done! Sorry for the delay :)

**Comment by 1st** [comment]
Thanks sir! :+1:

**Pull request merged**
