### PR TITLE
Another PDF fix!

### PR DESCRIPTION
**Pull request by stephenplusplus**
Hey,

I'm not sure if I just have a finicky computer, or if everyone else was having issues with PDF builds.

I tracked down some pesky errors:
1. The `ģ` in `Uģis Ozols` was bombing the build. I changed it to just a regular, ol' `Ugis` to fix it.  Sorry @ugisozols :(
2. There was a heading: `**$el and $()**` that was being stripped and output as: `elandpar`. I'm not an expert at this character encoding, and multi-translation build steps stuff. But, I at least was able to recognize `**$` didn't register as a heading, and threw the compiler off. I wasn't sure of a good fix, so I changed it to: `**el and $()**`, allowing the text that follows to explain.

I also removed a file, `/INSTRUCTIONS-pandoc-ebooks.md`, since I believe this step is covered in the Makefile.  

I'm not sure if you'll want to merge these in, considering the changes I had to make. But, if you think it's a fair trade-off, I'm happy to have helped! I'm also happy to be the un-official "build guy." Since the effort involved to resolve the various build dependencies and run it is much more intimidating than contributing text, I can gladly keep an eye on the repo to see if a build needs to be done!

### CODE REVIEW

**Comment by ugisozols** [comment]
My name is always causing problems :)

**Comment by ugisozols** [comment]
... I'm still curious why does it break on `ģ` and not on `ö` in Björn.

**Comment by addyosmani** [comment]
I really appreciate the effort taken to look at the build issues. I'm going to give this a once over and hopefully merge!

**Comment by stephenplusplus** [comment]
No problem! I just did a rebase-aroo.

**Comment by addyosmani** [comment]
Btw, haven't forgotten about this. As its the last few days before the book needs to be submitted to the publishers I'm holding off on any build changes but will hopefully be able to merge this in next week with less worry :)

**Comment by stephenplusplus** [comment]
Oh, cool! I completely understand. Hope everything goes smoothly!

**Pull request closed without merging**
