### PR TITLE
Fix image link

### PR DESCRIPTION
**Pull request by munen**

### CODE REVIEW

**Comment by addyosmani** [comment]
:+1:

**Comment by addyosmani** [comment]
I need to back this out. Erroneously thought it corrected a broken path, but our build process confirms the original was indeed correct. Next push should fix.

**Comment by munen** [comment]
@addyosmani I'm sorry for the confusion, I did not build the book, I merely read using Githubs' markdown parser where the path looks wrong (again^^).

Thanks for double checking!

backbone-fundamentals_06-extensions_md_at_gh-pages_ _addyosmani_backbone-fundamentals_-_vimperator-2

**Comment by addyosmani** [comment]
Aha! That makes complete sense (and no need to apologize at all!) :) I do appreciate the PRs and the other ones definitely helped. Because of the way the paths are referenced in HTML vs markdown from the repo, they may appear incorrect but are in fact okay :D

**Pull request merged**
