### PR TITLE
Use lower case first naming convention for objects

### PR DESCRIPTION
**Pull request by j-hannes**
Since `todo` and `todos` are an instantiated model and collection they should be written in lcfirst, not ucfirst. Looked too confusing anyway. ;)

### CODE REVIEW

**Comment by addyosmani** [comment]
Hmmm. So, I'm going to have to sit on this one as I re-review our strategy for lcfirst/ucfirst. I originally looked at what DocumentCloud were using for their casing and it appeared to suggest they favored ucfirst. Will do some more digging and make a call on this.

Thanks for the PR either way!

**Comment by j-hannes** [comment]
Ah no worries. Was expecting ucfirst for "classes" and lcfirst for objects. Actually assumed this one here was a mistake, but then found more ucfirst notations for objects when I continued reading.

**Comment by tryggve** [comment]
I found this confusing as well. Especially since the book doesn't use the ucfirst pattern consistently. I have only read the 'Backbone Basics' chapter about models, views and controllers but on several occasions I had to read the example over to be sure what you were saying.

Some examples:
In the 'Model' section: All the examples with todo's you use the ucfirst to declare a constructor function of a new class and then create instances of that class into variables with lcfirst. But then comes an example when you use 'Person' and instantiates an object directly into that.

Even more confusing is the section regarding Collections.
You start of with some examples declaring a constructor function called 'TodosCollection' and then you instantiates a collection out of that. But suddenly you do 'var TodosCollection = new.Backbone.Collection()' and start treating it like a collector instance in that example and several after that.
The twist comes when you use ucfirst in The Beatles example on the instances of the persons in the band =)

So, giving voice to the newbies from the community, please decide how you want to have it.

**Comment by addyosmani** [comment]
Sorry for taking so long to merge this in. There were a few other changes that needed to take priority. I would be happy for us to move ahead with @J-Hannes suggestion here. Will actively try to fix the other casing issues in the book. Help is of course welcome for anyone that has time and would like to help :)

**Comment by AnkitPatel123** [comment]
$(document).ready(function() {
  var todosCollection = new Backbone.Collection();
// log a message if a model in the collection changes
todosCollection.on("change:title", function(model) {
console.log("Changed my mind! I should " + model.get('title'));
});
todosCollection.add([
{ title: 'go to Jamaica.', completed: false, id: 3 },
]);
var mytodo = todosCollection.get(3);
mytodo.set('title', 'go fishing');
// Logs: Changed my mind! I should go fishing

});

**Comment by AnkitPatel123** [comment]
am getting thi s error:
TypeError: todosCollection.on is not a function
    todosCollection.on("change:title", function(model) {

**Pull request merged**
