### PR TITLE
defaults don't need to be a function

### PR DESCRIPTION
**Pull request by kimjoar**
I couldn't find a reason for not keeping all defaults as hash-only instead of a function which returns a hash.

### CODE REVIEW

**Comment by kimjoar** [comment]
Should I squash them and push a new (single) commit?

**Comment by addyosmani** [comment]
@kjbekkelund If you could that would be much appreciated :)

**Comment by kimjoar** [comment]
Squashed.

**Comment by addyosmani** [comment]
Thanks! Merging :)

**Pull request merged**
