### PR TITLE
http verbs order created confusion

### PR DESCRIPTION
**Pull request by hosseio**

### CODE REVIEW

**Comment by angelogulina** [comment]
I think "Create, Read, Update and Delete" is supposed to stay in that order since its acronym CRUD. It's sort of a standard by now.

**Comment by hosseio** [comment]
Ok. I suggested it because when reading it seems to me that get corresponds with Create, put with Read, etcetera.
Thank you for reviewing it :)

**Comment by angelogulina** [comment]
You're welcome :)
Generally speaking CRUD refers to action implemented in databases (Create, Read, Update and Delete). As far as I know, there's a rather tight correspondence with HTTP methods and all that's concerned with that (CREATE => POST, READ => GET, UPDATE => PUT, DELETE => DELETE). If interested, you can read more [here](http://en.wikipedia.org/wiki/Create,_read,_update_and_delete).

**Comment by hosseio** [comment]
I am familiar with it, thank you :) I was just thinking on beginners.
Good job here with the book.
Thank you and best regards!

**Comment by freethejazz** [comment]
Can this be closed?

**Comment by hosseio** [comment]
It can, yes

**Comment by freethejazz** [comment]
Can you do it? I don't have rights to do that here.

**Comment by hosseio** [comment]
Oh sure, sorry.

**Comment by freethejazz** [comment]
No worries, thanks!

**Pull request closed without merging**
