### PR TITLE
Editorial pass

### PR DESCRIPTION
**Pull request by heyotwell**
I've taken a pass at a light overall editorial cleanup. I've fixed some grammar errors, tightened up quite a few sentences, tried to make the overal tone of voice a bit more consistent, and removed a few bits that were redundant. I've stopped at the end of "Basics", but could continue into "Advanced" if you think this is helpful.

### CODE REVIEW

**Comment by addyosmani** [comment]
@heyotwell Thank you very much for taking the time to help tighten some of the sentences and clean-up grammatical errors, Andrew. It's much appreciated. I'll begin reviewing your changes in greater depth tomorrow, but if you have time to review the advanced section I would certainly be happy to look at any proposed cleanups you would recommend :)

**Comment by heyotwell** [comment]
Sure. And let me know if it'd be better to make more granular commits instead of a few monolithic ones.

**Comment by addyosmani** [comment]
@heyotwell whatever you're most comfortable with. I personally don't mind them in batch form :)

**Comment by addyosmani** [comment]
@heyotwell I've taken a look through your PR in more detail. Here's some feedback: 
- There are a number of lines I agree with updating and would like to
- Some of the recommended changes I'd like to hold off as they deviate from my writing style. Any grammatical errors will of course be included.
- There are some very minor typos in the PR which would be useful to get corrected

Would you be okay with me selectively updating the book manually with some of your changes and just referencing back to this PR?

**Comment by heyotwell** [comment]
Sure thing -- just use whatever you think is useful to you. Glad you found it helpful.

**Comment by addyosmani** [comment]
@heyotwell Just wanted to give you an update. I've finally integrated about 80% of your recommended editorial changes :)

These changes were made in 
- 05d211fb26cdbe606301e3c81860cf39d92dc9c6  
- 1f87b48b68350c841f362f726b754cd2c6dd5150
- 3a6d8e6a7e36c97524a23bef2cb3e22413811fbd

Thank you _so_ much once again for taking the time out to help with this. It's much appreciated. If there are any other revisions you would like to suggest for other parts of the book, please feel free to let me know.

**Comment by heyotwell** [comment]
Cool! I'll take a pass at the Advanced section too then. Glad it's been a help.

**Pull request closed without merging**
