### PR TITLE
Microtemplates interpolation settings (braces)

### PR DESCRIPTION
**Pull request by OpenGrid**
Added information how to change default <%= %> tag in Underscore Microtemplates to use braces {{ }}.
Some people feel more comfortable using braces and don't know that they can change the default settings instead of switching to another library.

### CODE REVIEW

**Comment by addyosmani** [comment]
I'm going to revise this slightly, but I'll merge then make my changes. Thanks!

**Comment by OpenGrid** [comment]
something is wrong with formatting right now

**Comment by addyosmani** [comment]
@OpenGrid I think this is fixed now. Can you confirm?

**Comment by OpenGrid** [comment]
@addyosmani confirmed :)

**Pull request merged**
